### ISSUE TITLE
Add density histogram

### ISSUE THREAD

**Issue by urmi-21** [urmi-21/MetaOmGraph#38]
**Is your feature request related to a problem? Please describe.**
Currently, the histogram plot shows the frequency of data. There should be an option to create normalized by sum histogram that would correspond to density.

**Describe the solution you'd like**
Add an option to the histogram plot to normalize histogram by total count.

**Comment by vksriharsha** [comment]
Can I work on this?

**Comment by urmi-21** [comment]
> 
> 
> Can I work on this?

Go for it. Thanks
